version: '3.7'

services:
  relay:
    container_name: relay_1
    build: .
    env_file:
      - ./.env
    ports:
    - 3001:3001
    volumes:
      - ${DATA_PATH}:/data
      - ${IPC_PATH}:/ipc
      - ${CONFIG_PATH}:/config
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    entrypoint: /home/cardano/start-relay.sh
