version: '3.7'

services:
  relay:
    container_name: cardano_relay
    build: .
    env_file:
      - ./.env
    ports:
    - 3001:3001
    volumes:
      - ${DATA_PATH}:/data
      - ${IPC_PATH}:/ipc
      - ${CONFIG_PATH}:/config
      - ${LOG_PATH}:/log
    restart: on-failure
    entrypoint: /home/cardano/start-relay.sh
